version: '3.9'

services:
  db:
    image: postgres

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db